import { useRef, useEffect } from 'react';
import { Animated, Text, View } from 'react-native';
import { theme } from '../../constants/theme';
import { GlassCard } from '../ui/GlassCard';
import { ProgressBar } from '../ui/ProgressBar';
import type { WidgetPayload } from '../../types';

const ACCENT = '#6D00FF';

type WidgetRendererProps = {
  widget: WidgetPayload;
  staggerIndex?: number;
};

function GenesisBadge() {
  return (
    <Text style={{ color: ACCENT, fontSize: 9, fontFamily: 'JetBrainsMonoMedium', marginTop: 8, opacity: 0.7 }}>
      GENERATED BY GENESIS
    </Text>
  );
}

function SlideIn({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) {
  const translateY = useRef(new Animated.Value(20)).current;
  const opacity = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const timer = setTimeout(() => {
      Animated.parallel([
        Animated.timing(translateY, { toValue: 0, duration: 300, useNativeDriver: true }),
        Animated.timing(opacity, { toValue: 1, duration: 300, useNativeDriver: true }),
      ]).start();
    }, delay);
    return () => clearTimeout(timer);
  }, [translateY, opacity, delay]);

  return (
    <Animated.View style={{ transform: [{ translateY }], opacity }}>
      {children}
    </Animated.View>
  );
}

// -- Priority Widgets (full implementation) --

function MetricCardWidget({ widget }: { widget: WidgetPayload }) {
  const trend = widget.data?.trend as string | undefined;
  const trendArrow = trend === 'up' ? '\u25B2' : trend === 'down' ? '\u25BC' : '';
  const trendColor = trend === 'up' ? '#00F5AA' : trend === 'down' ? '#FF6B6B' : theme.colors.textSecondary;

  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textSecondary, fontSize: 11, fontFamily: 'JetBrainsMonoMedium' }}>
        {widget.title ?? 'Metric'}
      </Text>
      <View style={{ flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 4 }}>
        <Text style={{ color: theme.colors.textPrimary, fontSize: 28, fontWeight: '700', fontFamily: 'JetBrainsMonoBold' }}>
          {String(widget.value ?? '--')}
        </Text>
        {trendArrow ? (
          <Text style={{ color: trendColor, fontSize: 14, fontWeight: '600' }}>
            {trendArrow}
          </Text>
        ) : null}
      </View>
      <GenesisBadge />
    </GlassCard>
  );
}

function WorkoutCardWidget({ widget }: { widget: WidgetPayload }) {
  const exercises = (widget.data?.exercises ?? []) as Array<{ name: string; sets?: number; reps?: number; load?: number }>;
  const note = widget.data?.note as string | undefined;

  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Workout'}
      </Text>
      {exercises.length > 0 ? (
        <View style={{ marginTop: 8, gap: 4 }}>
          {exercises.slice(0, 6).map((ex, i) => (
            <Text key={i} style={{ color: theme.colors.textSecondary, fontSize: 12, fontFamily: 'JetBrainsMonoMedium' }}>
              {ex.name}{ex.sets ? ` -- ${ex.sets}x${ex.reps ?? '?'}` : ''}{ex.load ? ` @ ${ex.load}kg` : ''}
            </Text>
          ))}
        </View>
      ) : (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 12, marginTop: 4 }}>
          {widget.data?.exercise_count ? `${widget.data.exercise_count} ejercicios` : 'Sin ejercicios listados'}
        </Text>
      )}
      {note ? (
        <Text style={{ color: ACCENT, fontSize: 11, marginTop: 8, fontStyle: 'italic' }}>{note}</Text>
      ) : null}
      <GenesisBadge />
    </GlassCard>
  );
}

function MealPlanWidget({ widget }: { widget: WidgetPayload }) {
  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Meal Plan'}
      </Text>
      <Text style={{ color: ACCENT, fontSize: 22, fontWeight: '700', fontFamily: 'JetBrainsMonoBold', marginTop: 4 }}>
        {String(widget.value ?? '--')}
      </Text>
      {widget.data?.meal_count ? (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 12, marginTop: 4 }}>
          {String(widget.data.meal_count)} comidas registradas
        </Text>
      ) : null}
      <GenesisBadge />
    </GlassCard>
  );
}

function HydrationTrackerWidget({ widget }: { widget: WidgetPayload }) {
  const glasses = Number(widget.data?.glasses ?? 0);
  const goal = Number(widget.data?.goal ?? 8);
  const pct = Math.min((glasses / goal) * 100, 100);

  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 14, fontWeight: '700' }}>
        {widget.title ?? 'Hidratacion'}
      </Text>
      <View style={{ marginTop: 8 }}>
        <ProgressBar progress={pct} color={ACCENT} />
      </View>
      <Text style={{ color: theme.colors.textSecondary, fontSize: 12, marginTop: 4 }}>
        {String(widget.value ?? `${glasses}/${goal} vasos`)}
      </Text>
      <GenesisBadge />
    </GlassCard>
  );
}

function ProgressDashboardWidget({ widget }: { widget: WidgetPayload }) {
  const completed = widget.data?.completed as number | undefined;
  const total = widget.data?.total as number | undefined;
  const prs = widget.data?.prs as number | undefined;
  const pct = total ? Math.min(((completed ?? 0) / total) * 100, 100) : Number(widget.value ?? 0);

  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Progress'}
      </Text>
      <View style={{ marginTop: 8 }}>
        <ProgressBar progress={pct} color={ACCENT} />
      </View>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }}>
        {completed != null && (
          <View>
            <Text style={{ color: theme.colors.textSecondary, fontSize: 10 }}>Completados</Text>
            <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>{completed}</Text>
          </View>
        )}
        {total != null && (
          <View>
            <Text style={{ color: theme.colors.textSecondary, fontSize: 10 }}>Total</Text>
            <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>{total}</Text>
          </View>
        )}
        {prs != null && (
          <View>
            <Text style={{ color: theme.colors.textSecondary, fontSize: 10 }}>PRs</Text>
            <Text style={{ color: ACCENT, fontSize: 16, fontWeight: '700' }}>{prs}</Text>
          </View>
        )}
      </View>
      <GenesisBadge />
    </GlassCard>
  );
}

function InsightCardWidget({ widget }: { widget: WidgetPayload }) {
  return (
    <GlassCard>
      <Text style={{ color: ACCENT, fontSize: 11, fontWeight: '700', fontFamily: 'JetBrainsMonoMedium' }}>
        Insight
      </Text>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 14, marginTop: 4 }}>
        {widget.title ?? 'Insight'}
      </Text>
      {widget.value ? (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 12, marginTop: 2 }}>
          {String(widget.value)}
        </Text>
      ) : null}
      {widget.subtitle ? (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 12, marginTop: 2 }}>
          {widget.subtitle}
        </Text>
      ) : null}
      <GenesisBadge />
    </GlassCard>
  );
}

function SeasonTimelineWidget({ widget }: { widget: WidgetPayload }) {
  const status = widget.data?.status as string | undefined;
  const startDate = widget.data?.start_date as string | undefined;
  const endDate = widget.data?.end_date as string | undefined;

  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Season'}
      </Text>
      {status ? (
        <View style={{ backgroundColor: `${ACCENT}22`, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, alignSelf: 'flex-start', marginTop: 6 }}>
          <Text style={{ color: ACCENT, fontSize: 10, fontWeight: '700', textTransform: 'uppercase' }}>{status}</Text>
        </View>
      ) : null}
      {startDate && endDate ? (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 11, marginTop: 6 }}>
          {startDate} - {endDate}
        </Text>
      ) : null}
      <GenesisBadge />
    </GlassCard>
  );
}

function TodayCardWidget({ widget }: { widget: WidgetPayload }) {
  const mood = widget.data?.mood;
  const energy = widget.data?.energy;
  const sleepHours = widget.data?.sleep_hours;

  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Hoy'}
      </Text>
      <View style={{ flexDirection: 'row', gap: 16, marginTop: 8 }}>
        {mood != null && (
          <View>
            <Text style={{ color: theme.colors.textSecondary, fontSize: 10 }}>Animo</Text>
            <Text style={{ color: theme.colors.textPrimary, fontSize: 18, fontWeight: '700' }}>{String(mood)}</Text>
          </View>
        )}
        {energy != null && (
          <View>
            <Text style={{ color: theme.colors.textSecondary, fontSize: 10 }}>Energia</Text>
            <Text style={{ color: theme.colors.textPrimary, fontSize: 18, fontWeight: '700' }}>{String(energy)}</Text>
          </View>
        )}
        {sleepHours != null && (
          <View>
            <Text style={{ color: theme.colors.textSecondary, fontSize: 10 }}>Sueno</Text>
            <Text style={{ color: theme.colors.textPrimary, fontSize: 18, fontWeight: '700' }}>{String(sleepHours)}h</Text>
          </View>
        )}
      </View>
      <GenesisBadge />
    </GlassCard>
  );
}

// -- Simple Widgets (GlassCard + title + value) --

function SimpleWidget({ widget }: { widget: WidgetPayload }) {
  return (
    <GlassCard>
      <Text style={{ color: theme.colors.textPrimary, fontSize: 14, fontWeight: '700' }}>
        {widget.title ?? 'Widget'}
      </Text>
      {widget.value != null ? (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 12, marginTop: 4 }}>
          {String(widget.value)}
        </Text>
      ) : null}
      {widget.subtitle ? (
        <Text style={{ color: theme.colors.textSecondary, fontSize: 11, marginTop: 2 }}>
          {widget.subtitle}
        </Text>
      ) : null}
      <GenesisBadge />
    </GlassCard>
  );
}

// -- Main Renderer --

export function WidgetRenderer({ widget, staggerIndex }: WidgetRendererProps) {
  const content = (() => {
    switch (widget.type) {
      case 'metric-card':
        return <MetricCardWidget widget={widget} />;
      case 'workout-card':
        return <WorkoutCardWidget widget={widget} />;
      case 'meal-plan':
        return <MealPlanWidget widget={widget} />;
      case 'hydration-tracker':
        return <HydrationTrackerWidget widget={widget} />;
      case 'progress-dashboard':
        return <ProgressDashboardWidget widget={widget} />;
      case 'insight-card':
        return <InsightCardWidget widget={widget} />;
      case 'season-timeline':
        return <SeasonTimelineWidget widget={widget} />;
      case 'today-card':
        return <TodayCardWidget widget={widget} />;
      default:
        return <SimpleWidget widget={widget} />;
    }
  })();

  return <SlideIn delay={(staggerIndex ?? 0) * 100}>{content}</SlideIn>;
}
