import { Text, View } from 'react-native';
import Animated, { FadeInUp } from 'react-native-reanimated';
import { LinearGradient } from 'expo-linear-gradient';
import { GENESIS_COLORS } from '../../constants/colors';
import { LiquidGlassCard } from '../ui/LiquidGlassCard';
import { ProgressBar } from '../ui/ProgressBar';
import { BreathworkWidget } from './widgets/BreathworkWidget';
import { MeditationWidget } from './widgets/MeditationWidget';
import { JournalWidget } from './widgets/JournalWidget';
import { VideoEmbedWidget } from './widgets/VideoEmbedWidget';
import { RecipeCardWidget } from './widgets/RecipeCardWidget';
import { QuickCheckinWidget } from './widgets/QuickCheckinWidget';
import { OnboardingFormWidget } from './widgets/OnboardingFormWidget';
import { PhotoComparisonWidget } from './widgets/PhotoComparisonWidget';
import type { WidgetPayload } from '../../types';

const ACCENT = '#6D00FF';

/** Wrapper that provides consistent padding inside LiquidGlassCard */
function WidgetCard({ children }: { children: React.ReactNode }) {
  return (
    <LiquidGlassCard effect="regular" borderRadius={16}>
      <View style={{ padding: 16 }}>{children}</View>
    </LiquidGlassCard>
  );
}

type WidgetRendererProps = {
  widget: WidgetPayload;
  staggerIndex?: number;
};

function GenesisBadge() {
  return (
    <Text style={{ color: ACCENT, fontSize: 9, fontFamily: 'JetBrainsMonoMedium', marginTop: 8, opacity: 0.7 }}>
      GENERATED BY GENESIS
    </Text>
  );
}

/** 2px violet gradient line at the top of each widget. */
function WidgetAccent() {
  return (
    <LinearGradient
      colors={[GENESIS_COLORS.primary, 'transparent']}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 0 }}
      style={{ width: 40, height: 2, borderRadius: 1, marginBottom: 10 }}
    />
  );
}

// -- Priority Widgets --

function MetricCardWidget({ widget }: { widget: WidgetPayload }) {
  const trend = widget.data?.trend as string | undefined;
  const trendArrow = trend === 'up' ? '\u25B2' : trend === 'down' ? '\u25BC' : '';
  const trendColor = trend === 'up' ? '#00F5AA' : trend === 'down' ? '#FF6B6B' : GENESIS_COLORS.textSecondary;

  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 11, fontFamily: 'JetBrainsMonoMedium' }}>
        {widget.title ?? 'Metric'}
      </Text>
      <View style={{ flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 4 }}>
        <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 28, fontFamily: 'JetBrainsMonoBold' }}>
          {String(widget.value ?? '--')}
        </Text>
        {trendArrow ? (
          <Text style={{ color: trendColor, fontSize: 14, fontWeight: '600' }}>
            {trendArrow}
          </Text>
        ) : null}
      </View>
      <GenesisBadge />
    </WidgetCard>
  );
}

function WorkoutCardWidget({ widget }: { widget: WidgetPayload }) {
  const exercises = (widget.data?.exercises ?? []) as Array<{ name: string; sets?: number; reps?: number; load?: number }>;
  const note = widget.data?.note as string | undefined;

  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Workout'}
      </Text>
      {exercises.length > 0 ? (
        <View style={{ marginTop: 8, gap: 4 }}>
          {exercises.slice(0, 6).map((ex, i) => (
            <Text key={i} style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, fontFamily: 'JetBrainsMonoMedium' }}>
              {ex.name}{ex.sets ? ` -- ${ex.sets}x${ex.reps ?? '?'}` : ''}{ex.load ? ` @ ${ex.load}kg` : ''}
            </Text>
          ))}
        </View>
      ) : (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, marginTop: 4 }}>
          {widget.data?.exercise_count ? `${widget.data.exercise_count} ejercicios` : 'Sin ejercicios listados'}
        </Text>
      )}
      {note ? (
        <Text style={{ color: ACCENT, fontSize: 11, marginTop: 8, fontStyle: 'italic' }}>{note}</Text>
      ) : null}
      <GenesisBadge />
    </WidgetCard>
  );
}

function MealPlanWidget({ widget }: { widget: WidgetPayload }) {
  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Meal Plan'}
      </Text>
      <Text style={{ color: ACCENT, fontSize: 22, fontFamily: 'JetBrainsMonoBold', marginTop: 4 }}>
        {String(widget.value ?? '--')}
      </Text>
      {widget.data?.meal_count ? (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, marginTop: 4 }}>
          {String(widget.data.meal_count)} comidas registradas
        </Text>
      ) : null}
      <GenesisBadge />
    </WidgetCard>
  );
}

function HydrationTrackerWidget({ widget }: { widget: WidgetPayload }) {
  const glasses = Number(widget.data?.glasses ?? 0);
  const goal = Number(widget.data?.goal ?? 8);
  const pct = Math.min((glasses / goal) * 100, 100);

  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 14, fontWeight: '700' }}>
        {widget.title ?? 'Hidratación'}
      </Text>
      <View style={{ marginTop: 8 }}>
        <ProgressBar progress={pct} color={ACCENT} />
      </View>
      <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, fontFamily: 'JetBrainsMonoMedium', marginTop: 4 }}>
        {String(widget.value ?? `${glasses}/${goal} vasos`)}
      </Text>
      <GenesisBadge />
    </WidgetCard>
  );
}

function ProgressDashboardWidget({ widget }: { widget: WidgetPayload }) {
  const completed = widget.data?.completed as number | undefined;
  const total = widget.data?.total as number | undefined;
  const prs = widget.data?.prs as number | undefined;
  const pct = total ? Math.min(((completed ?? 0) / total) * 100, 100) : Number(widget.value ?? 0);

  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Progress'}
      </Text>
      <View style={{ marginTop: 8 }}>
        <ProgressBar progress={pct} color={ACCENT} />
      </View>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }}>
        {completed != null && (
          <View>
            <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 10 }}>Completados</Text>
            <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontFamily: 'JetBrainsMonoBold' }}>{completed}</Text>
          </View>
        )}
        {total != null && (
          <View>
            <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 10 }}>Total</Text>
            <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontFamily: 'JetBrainsMonoBold' }}>{total}</Text>
          </View>
        )}
        {prs != null && (
          <View>
            <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 10 }}>PRs</Text>
            <Text style={{ color: ACCENT, fontSize: 16, fontFamily: 'JetBrainsMonoBold' }}>{prs}</Text>
          </View>
        )}
      </View>
      <GenesisBadge />
    </WidgetCard>
  );
}

function InsightCardWidget({ widget }: { widget: WidgetPayload }) {
  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: ACCENT, fontSize: 11, fontWeight: '700', fontFamily: 'JetBrainsMonoMedium' }}>
        Insight
      </Text>
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 14, marginTop: 4 }}>
        {widget.title ?? 'Insight'}
      </Text>
      {widget.value ? (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, marginTop: 2 }}>
          {String(widget.value)}
        </Text>
      ) : null}
      {widget.subtitle ? (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, marginTop: 2 }}>
          {widget.subtitle}
        </Text>
      ) : null}
      <GenesisBadge />
    </WidgetCard>
  );
}

function SeasonTimelineWidget({ widget }: { widget: WidgetPayload }) {
  const status = widget.data?.status as string | undefined;
  const startDate = widget.data?.start_date as string | undefined;
  const endDate = widget.data?.end_date as string | undefined;

  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Season'}
      </Text>
      {status ? (
        <View style={{ backgroundColor: `${ACCENT}22`, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, alignSelf: 'flex-start', marginTop: 6 }}>
          <Text style={{ color: ACCENT, fontSize: 10, fontWeight: '700', textTransform: 'uppercase' }}>{status}</Text>
        </View>
      ) : null}
      {startDate && endDate ? (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 11, fontFamily: 'JetBrainsMonoMedium', marginTop: 6 }}>
          {startDate} - {endDate}
        </Text>
      ) : null}
      <GenesisBadge />
    </WidgetCard>
  );
}

function TodayCardWidget({ widget }: { widget: WidgetPayload }) {
  const mood = widget.data?.mood;
  const energy = widget.data?.energy;
  const sleepHours = widget.data?.sleep_hours;

  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Hoy'}
      </Text>
      <View style={{ flexDirection: 'row', gap: 16, marginTop: 8 }}>
        {mood != null && (
          <View>
            <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 10 }}>Animo</Text>
            <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 18, fontFamily: 'JetBrainsMonoBold' }}>{String(mood)}</Text>
          </View>
        )}
        {energy != null && (
          <View>
            <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 10 }}>Energia</Text>
            <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 18, fontFamily: 'JetBrainsMonoBold' }}>{String(energy)}</Text>
          </View>
        )}
        {sleepHours != null && (
          <View>
            <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 10 }}>Sueno</Text>
            <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 18, fontFamily: 'JetBrainsMonoBold' }}>{String(sleepHours)}h</Text>
          </View>
        )}
      </View>
      <GenesisBadge />
    </WidgetCard>
  );
}

// -- Simple Widget (fallback) --

function SimpleWidget({ widget }: { widget: WidgetPayload }) {
  return (
    <WidgetCard>
      <WidgetAccent />
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 14, fontWeight: '700' }}>
        {widget.title ?? 'Widget'}
      </Text>
      {widget.value != null ? (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 12, marginTop: 4 }}>
          {String(widget.value)}
        </Text>
      ) : null}
      {widget.subtitle ? (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 11, marginTop: 2 }}>
          {widget.subtitle}
        </Text>
      ) : null}
      <GenesisBadge />
    </WidgetCard>
  );
}

// -- Main Renderer --

export function WidgetRenderer({ widget, staggerIndex }: WidgetRendererProps) {
  const content = (() => {
    switch (widget.type) {
      case 'metric-card':
        return <MetricCardWidget widget={widget} />;
      case 'workout-card':
        return <WorkoutCardWidget widget={widget} />;
      case 'meal-plan':
        return <MealPlanWidget widget={widget} />;
      case 'hydration-tracker':
        return <HydrationTrackerWidget widget={widget} />;
      case 'progress-dashboard':
        return <ProgressDashboardWidget widget={widget} />;
      case 'insight-card':
        return <InsightCardWidget widget={widget} />;
      case 'season-timeline':
        return <SeasonTimelineWidget widget={widget} />;
      case 'today-card':
        return <TodayCardWidget widget={widget} />;
      case 'breathwork':
        return <BreathworkWidget widget={widget} />;
      case 'meditation':
        return <MeditationWidget widget={widget} />;
      case 'journal':
        return <JournalWidget widget={widget} />;
      case 'video-embed':
        return <VideoEmbedWidget widget={widget} />;
      case 'recipe-card':
        return <RecipeCardWidget widget={widget} />;
      case 'quick-checkin':
        return <QuickCheckinWidget widget={widget} />;
      case 'onboarding-form':
        return <OnboardingFormWidget widget={widget} />;
      case 'photo-comparison':
        return <PhotoComparisonWidget widget={widget} />;
      default:
        return <SimpleWidget widget={widget} />;
    }
  })();

  return (
    <Animated.View
      entering={FadeInUp.delay((staggerIndex ?? 0) * 100)
        .duration(300)
        .springify()
        .damping(18)}
    >
      {content}
    </Animated.View>
  );
}
