import { Text, View } from 'react-native';
import { Play, CheckCircle } from 'lucide-react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { GlassCard } from '../../ui/GlassCard';
import { GENESIS_COLORS } from '../../../constants/colors';
import type { WidgetPayload } from '../../../types';

export function VideoEmbedWidget({ widget }: { widget: WidgetPayload }) {
  const keyPoints = (widget.data?.keyPoints as string[]) ?? [];
  const duration = (widget.data?.duration as string) ?? '';
  const category = (widget.data?.category as string) ?? '';

  return (
    <GlassCard>
      {/* Video thumbnail placeholder */}
      <View
        style={{
          height: 160,
          borderRadius: 12,
          overflow: 'hidden',
          marginBottom: 16,
        }}
      >
        <LinearGradient
          colors={[GENESIS_COLORS.primaryDark, '#1a0a3e', GENESIS_COLORS.bgGradientStart]}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={{
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          {/* Play button overlay */}
          <View
            style={{
              width: 56,
              height: 56,
              borderRadius: 28,
              backgroundColor: 'rgba(109, 0, 255, 0.6)',
              alignItems: 'center',
              justifyContent: 'center',
              borderWidth: 2,
              borderColor: 'rgba(255,255,255,0.2)',
            }}
          >
            <Play size={24} color="#FFFFFF" fill="#FFFFFF" />
          </View>
          {/* "Video disponible" label */}
          <Text
            style={{
              color: 'rgba(255,255,255,0.6)',
              fontSize: 11,
              fontFamily: 'JetBrainsMonoMedium',
              marginTop: 10,
            }}
          >
            VIDEO DISPONIBLE
          </Text>
        </LinearGradient>
      </View>

      {/* Video title */}
      <Text style={{ color: GENESIS_COLORS.textPrimary, fontSize: 16, fontWeight: '700' }}>
        {widget.title ?? 'Video'}
      </Text>

      {/* Meta row: duration + category */}
      {(duration || category) && (
        <View style={{ flexDirection: 'row', gap: 12, marginTop: 6 }}>
          {duration ? (
            <Text style={{ color: GENESIS_COLORS.textMuted, fontSize: 11, fontFamily: 'JetBrainsMonoMedium' }}>
              {duration}
            </Text>
          ) : null}
          {category ? (
            <View
              style={{
                backgroundColor: `${GENESIS_COLORS.primary}22`,
                borderRadius: 6,
                paddingHorizontal: 8,
                paddingVertical: 2,
              }}
            >
              <Text
                style={{
                  color: GENESIS_COLORS.primary,
                  fontSize: 10,
                  fontWeight: '700',
                  textTransform: 'uppercase',
                }}
              >
                {category}
              </Text>
            </View>
          ) : null}
        </View>
      )}

      {/* Subtitle / description */}
      {widget.subtitle && (
        <Text style={{ color: GENESIS_COLORS.textSecondary, fontSize: 13, marginTop: 8, lineHeight: 18 }}>
          {widget.subtitle}
        </Text>
      )}

      {/* Key points */}
      {keyPoints.length > 0 && (
        <View style={{ marginTop: 14, gap: 8 }}>
          <Text
            style={{
              color: GENESIS_COLORS.textSecondary,
              fontSize: 11,
              fontFamily: 'JetBrainsMonoMedium',
              textTransform: 'uppercase',
            }}
          >
            Puntos clave
          </Text>
          {keyPoints.map((point, i) => (
            <View key={i} style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 8 }}>
              <CheckCircle
                size={14}
                color={GENESIS_COLORS.primary}
                style={{ marginTop: 1 }}
              />
              <Text
                style={{
                  color: GENESIS_COLORS.textSecondary,
                  fontSize: 13,
                  fontFamily: 'Inter',
                  lineHeight: 18,
                  flex: 1,
                }}
              >
                {point}
              </Text>
            </View>
          ))}
        </View>
      )}

      {/* GENESIS badge */}
      <Text
        style={{
          color: GENESIS_COLORS.primary,
          fontSize: 9,
          fontFamily: 'JetBrainsMonoMedium',
          marginTop: 12,
          opacity: 0.7,
        }}
      >
        GENERATED BY GENESIS
      </Text>
    </GlassCard>
  );
}
